app:
    path: /
    defaults:
        _controller: AppBundle:Default:index

app_pass:
    path: /pass
    defaults:
        _controller: AppBundle:Default:index

app_etag:
    path: /etag
    defaults:
        _controller: AppBundle:Default:etag
    methods:  [GET]

app_content_create:
    path: /etag
    defaults:
        _controller: AppBundle:Default:contentCreate
    methods:  [POST]
